# Common -----------------------------------------------------------------------
use_cuda: True
device: "cuda:0"

# log -----------------------------------------------------------------------
log_format: '%(asctime)s - %(levelname)s - %(message)s'
enable_console_log: True
console_log_level: DEBUG
enable_file_log: False
file_log_level: DEBUG
file_log_path: ./log/operating.log

# Mesh -------------------------------------------------------------------------
model_path: data/three_dimensional_model/audi_etron/audi_etron.obj
face_path: data/three_dimensional_model/audi_etron/merged_output.txt
texture_size: 10
texture_map_save_path: ./output

# Render -----------------------------------------------------------------------
scale: 0.97
render_image_size: 1152
light: [ 0.0, 10.0, 0.0 ]
blur_radius: 0  # [0, 2]
faces_per_pixel: 1
bin_size:
max_faces_opengl: 10000000
max_faces_per_bin:
perspective_correct:
clip_barycentric_coords:
cull_backfaces: False
z_clip_value:
cull_to_frustum: False

# dataset -------------------------------------------------------------------
dataset_path: data/dataset/package
dataset_size: 1
all_dataset: True

# Detector -------------------------------------------------------------------
img_sz: [1152,1152]
conf_thres: 0.25
iou_thres: 0.45
max_det: 1000
view_img: False
save_boxes: True
save_conf: True
classes: 2
agnostic_nms: False
visualize: False
augment: True
line_thickness: 3
hide_labels: False
hide_conf: False
save_crop: False
save_img: True
only_objectness: False
train_classes: 2
# yolov5
yolov5_weights: "detector/neural_networks/neural_network_model_weights/yolov5x6.pt"
# yolov6
yolov6_weights: "detector/neural_networks/neural_network_model_weights/yolov6m.pt"
yaml: detector/neural_networks/yolov6/data/coco.yaml
half: False
# yolov7
yolov7_weights: "detector/neural_networks/neural_network_model_weights/yolov7.pt"

# clean --------------------------------------------------------------
clean_conf_threshold: 0.25
clean_iou_threshold: 0.45
cleaning: True
cleaning_result_path: "output/cleaning_result.txt"

# train --------------------------------------------------------------
train_dataset_path: data/dataset/package
epochs: 2
batch_size: 1
lr: 0.03
add_brightness: True
min_brightness: -0.2
max_brightness: 0.2
add_contrast: True
min_contrast: 0.8
max_contrast: 1.2
add_noise: True
noise_intensity: 0.1
mps_weight: 1000
tv_weight: 25
save_camo_to_pth: False
save_camo_pth_path: "output/final_camo.pth"
save_camo_to_png: True

# test --------------------------------------------------------------
test_dataset_path: data/dataset/radius_7/test
test_result_path: "output/test"
