# Common -----------------------------------------------------------------------
use_cuda: True
device: "cuda:0"

# log -----------------------------------------------------------------------
log_format: '%(asctime)s - %(levelname)s - %(message)s'
enable_console_log: True
console_log_level: DEBUG
enable_file_log: False
file_log_level: DEBUG
file_log_path: ./log/operating.log

# Mesh -------------------------------------------------------------------------
model_path: data/three_dimensional_model/audi_etron/audi_etron.obj
face_path: data/three_dimensional_model/audi_etron/merged_output.txt
texture_size: 32
texture_map_save_path: ./output

# Render -----------------------------------------------------------------------
render_image_size: 1152
light: [ 0.0, 10.0, 0.0 ]
blur_radius: 0 #[0,2]
faces_per_pixel: 1
bin_size:
max_faces_opengl: 10000000
max_faces_per_bin:
perspective_correct:
clip_barycentric_coords:
cull_backfaces: False
z_clip_value:
cull_to_frustum: False