# Common -----------------------------------------------------------------------
use_cuda: True
device: "cuda:0"
detector: yolov5

# log -----------------------------------------------------------------------
log_format: '%(asctime)s - %(levelname)s - %(message)s'
enable_console_log: True
console_log_level: DEBUG
enable_file_log: False
file_log_level: DEBUG
file_log_path: ./log/operating.log

# Mesh -------------------------------------------------------------------------
model_path: data/three_dimensional_model/audi_etron/audi_etron.obj
face_path: data/three_dimensional_model/audi_etron/merged_output.txt
texture_size: 50


# Render -----------------------------------------------------------------------
camo_init_random: False
scale: 0.97
render_image_size: 1152
light: [ 0.0, 10.0, 0.0 ]
#light: [ 2.0, 10.0, 5.0 ]
blur_radius: 0  # [0, 2]
faces_per_pixel: 1
bin_size:
max_faces_opengl: 10000000
max_faces_per_bin:
perspective_correct:
clip_barycentric_coords:
cull_backfaces: False
z_clip_value:
cull_to_frustum: False

# dataset -------------------------------------------------------------------
dataset_size: 10
all_dataset: True
shuffle: True

# Detector -------------------------------------------------------------------
img_sz: [1152,1152]
conf_thres: 0.25
iou_thres: 0.45
max_det: 1000
view_img: False
save_boxes: True
save_conf: True
classes: 2
agnostic_nms: False
visualize: False
augment: False
line_thickness: 3
hide_labels: False
hide_conf: False
save_crop: False
save_img: True
only_objectness: False
train_classes: 2
# yolov5
yolov5_weights: detector/neural_networks/neural_network_model_weights/yolov5x6.pt
# yolov6
yolov6_weights: detector/neural_networks/neural_network_model_weights/yolov6m.pt
yaml: detector/neural_networks/yolov6/data/coco.yaml
half: False
# yolov7
yolov7_weights: detector/neural_networks/neural_network_model_weights/yolov7.pt
#yolov8
yolov8_weights: detector/neural_networks/neural_network_model_weights/yolov8x.pt
verbose: True
# yolov9
yolov9_weights: detector/neural_networks/neural_network_model_weights/yolov9-e-converted.pt

# clean --------------------------------------------------------------
cleaning_dataset_path: data/dataset/
clean_conf_threshold: 0.25
clean_iou_threshold: 0.45
cleaning: True
cleaning_result_path: output/cleaning_result.txt

# train --------------------------------------------------------------
continue_train: False
camo_pth_path: output/result/12-26/checkpoint_epoch_500/track4-500.pth
train_dataset_path: data/dataset/10m/train
epochs: 500
batch_size: 1
#lr: 1e-14
#lr: 0.000001
lr: 0.0001
add_brightness: True
min_brightness: -0.1
max_brightness: 0.1
add_contrast: True
min_contrast: 0.8
max_contrast: 1.2
add_noise: True
noise_intensity: 0.1
mps_weight: 1000
tv_weight: 2

# test --------------------------------------------------------------
test_dataset_path: data/dataset/10m/extend

# save --------------------------------------------------------------
enable_save: True
save_folder: experiment

save_config: True
save_config_name: base_config.yaml

save_camo_to_pth: True
save_camo_pth_name: track4-500.pth

save_camo_to_png: True
save_camo_png_name: tracker5-set_camo

# ostracker----------------------------------------------------------
tracker_name: ostrack
tracker_param: vitb_256_mae_ce_32x4_ep300
dataset_name: local_data_train
run_id:
sequence:
debug: 0
threads: 0
num_gpus: 8
got10k_path: /home/he/project_code/Recognition-Confuse-Camo-Coating/detector/neural_networks/track/OSTrack/data/got10k
local_data_path: /home/he/project_code/Recognition-Confuse-Camo-Coating/detector/neural_networks/track/OSTrack/data/local_data
network_path: /home/he/project_code/Recognition-Confuse-Camo-Coating/detector/neural_networks/track/OSTrack/output/test/networks
results_path: /home/he/project_code/Recognition-Confuse-Camo-Coating/detector/neural_networks/track/OSTrack/output/test/tracking_results
save_dir: /home/he/project_code/Recognition-Confuse-Camo-Coating/detector/neural_networks/track/OSTrack/output
params:
  template_size: 128
  template_factor: 2
  search_factor: 4
  search_size: 256
cfg:
  MODEL:
    BACKBONE:
      CE_LOC: [2, 6, 9]
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
track_mps_weight: 7500
loss_weight:
  giou: 2.0
  l1: 5.0
  focal: 1.0
search_size: 256
backbone_stride: 16
